apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ai-tutor-staging
spec:
  selector:
    app: ai-tutor-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
