apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ai-dev
  labels:
    app: ai-tutor-frontend
spec:
  selector:
    app: ai-tutor-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
