apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-prod
  namespace: ai-tutor-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Prod: Larger storage
